weights: NPS-640_uav_s.pt
cfg: models/NPS_uav_s.yaml
data: data/ARD100_mask32.yaml
hyp: data/hyps/hyp.scratch-low.yaml
epochs: 80
batch_size: 24
imgsz: 1280
rect: false
resume: ''
nosave: false
noval: false
noautoanchor: false
evolve: null
bucket: ''
cache: null
image_weights: false
device: 0,1,2,3
multi_scale: false
single_cls: false
optimizer: SGD
sync_bn: false
workers: 8
project: runs/train
name: ARD100_mask32-1280_uavs
exist_ok: false
quad: false
cos_lr: false
label_smoothing: 0.0
patience: 100
freeze:
- 0
save_period: -1
local_rank: -1
entity: null
upload_dataset: false
bbox_interval: -1
save_dir: runs/train/ARD100_mask32-1280_uavs2
